openapi: 3.0.0
servers: []
info:
  description: Common object Definitions for PFM
  version: "1.0.0"
  title: PFM Common Definitions

paths: {}

components:
  schemas:
    RequestHeader:
      type: object
      properties:
        requestMessageId:
          type: string
          format: uuid
        correlationId:
          type: string
          format: uuid
        authToken: 
          type: string
        apiId:
          type: string
        apiVersion:
          type: string
        deviceId:
          type: string
        timestamp:
          type: integer
          format: int64

    ResponseHeader:
      type: object
      properties:
        responseMessageId:
          type: string
          format: uuid
        requestMessageId:
          type: string
          format: uuid
        correlationId: 
          type: string
          format: uuid
        status:
          type: string
          enum: 
            - Success
            - Accepted
            - Failed