openapi: 3.0.0
info:
  description: |
    Public Finance Management - User Registry
  version: "1.0.0"
  title: PFM User Registry

paths:
  '/user/v1/_create':
    post:
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '200':
          description: User created successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Error occurred while creating the user
  
  '/user/v1/_update':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Error occurred while updating the user
  
  '/user/v1/_delete':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDeleteRequest'
      responses:
        '200': 
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Error occurred while deleting the user
  
  '/user/v1/_cancel':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDeleteRequest'
      responses:
        '200':
          description: User deactivated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Error occurred while deactivating the user
          
  '/user/v1/_search':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSearchRequest'
      responses:
        '200':
          description: User Search Results
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseHeader:
                    $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/ResponseHeader'
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
            
components:
  schemas:
    User:
      type: object
      properties:
        tenantId:
          type: string
          example: 'in'
        username:
          type: string
        uuid:
          type: string
          format: uuid
          example: 'abcd-wxyz'
        pin:
          type: string
        mobileNumber:
          type: string
          example: '9123123123'
        emailId:
          type: string
          example: 'mail@egov.org.in'
        aadharNumber:
          type: string
          example: '1234-5678'
        address:
          type: string
        roles:
          type: array
          items: 
            type: string
            example: 'Approver'
    UserCreateRequest:
      type: object
      properties:
        requestHeader: 
          $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/RequestHeader'
        user:
          type: object
          allOf:
            - $ref: '#/components/schemas/User'
            - required: 
              - username
              - tenantId
    UserUpdateRequest:
      type: object
      properties:
        requestHeader: 
          $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/RequestHeader'
        user:
          type: object
          allOf:
            - $ref: '#/components/schemas/User'
            - required: 
              - uuid
              - tenantId
    UserDeleteRequest:
      type: object
      properties:
        requestHeader: 
          $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/RequestHeader'
        user:
          type: object
          properties:
            tenantId:
              type: string
            uuid: 
              type: string
          required:
            - tenantId
            - uuid
    UserSearchRequest:
      type: object
      properties:
        requestHeader: 
          $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/RequestHeader'
        userSearchParams:
          type: object
          properties:
            tenantId:
              type: string
            uuid:
              type: string
            pin: 
              type: string
            mobileNumber:
              type: string
            emailId:
              type: string
            aadharNumber:
              type: string
          required:
            - tenantId
    UserResponse:
      type: object
      properties:
        responseHeader:
          $ref: 'https://raw.githubusercontent.com/rushang7-eGov/OpenAPIContracts/master/PFM/PFM-Common-Definitions.yaml#/components/schemas/ResponseHeader'
        user:
          $ref: '#/components/schemas/User'